name: test_unlinked
description: ''
version: 0.0.1
author: nimbus@simpledatalabs.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: test_unlinked
  parentArtefactID: nathanprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-09-22 00:00:49'
pipelines:
  pipelines/scd1_python:
    name: scd1_merge
    description: "These series of gems perform various operations to demonstrate a\
      \ SCD type 1 change from a source CSV file to a target Delta table. \n\nThis\
      \ pipeline uses the sample Databricks retail-org dataset and splits the data\
      \ into three dataframes simulating unchanged rows, updated rows, and new rows."
    author: nimbus@simpledatalabs.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-08-01 20:21:29'
    datasets:
      inputs:
      - datasets/customers_raw
      - datasets/customers_scd1
      outputs:
      - datasets/customers_scd1
    subgraphs:
    - subgraphs/GenerateRandomIncrement
    dependencies: {}
  pipelines/scd2_merge:
    name: scd2_merge
    description: Type 2 SCD Merge using CSV and Delta
    author: nathan@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-09-22 00:06:08'
    datasets:
      inputs:
      - datasets/customers_raw
      - datasets/customers_scd2
      outputs:
      - datasets/customers_scd2
    subgraphs:
    - subgraphs/GenerateRandomIncrement
    dependencies: {}
datasets:
  datasets/customers_scd1:
    name: customers_scd1
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-01 21:20:54'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-01 21:20:54'
  datasets/customers_raw:
    name: customers_raw
    description: ''
    author: nimbus@simpledatalabs.com
    createdAt: '2022-08-01 20:24:44'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 51
        datasetType: File
        description: ''
        author: nimbus@simpledatalabs.com
        createdAt: '2022-08-01 20:24:44'
  datasets/customers_scd2:
    name: customers_scd2
    description: ''
    author: nathan@prophecy.io
    createdAt: '2023-09-22 00:11:59'
    mode: batch
    physicalDatasets:
      DBX_SalesEng:
        fabricId: 4678
        datasetType: File
        description: ''
        author: nathan@prophecy.io
        createdAt: '2023-09-22 00:11:59'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-09-22 00:00:49'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs:
  subgraphs/GenerateRandomIncrement:
    name: GenerateRandomIncrement
    description: ''
    author: nimbus@simpledatalabs.com
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2022-08-01 21:30:37'
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-07-12T12:52:30.757377Z'
  name: plibMaven
  version: 8.0.25
  id: '2096666076'
  createdAt: '2024-07-12T12:52:30.757347Z'
- type: plibPypi
  modifiedAt: '2024-07-12T12:52:30.757435Z'
  name: plibPypi
  version: 1.9.9
  id: '1794322909'
  createdAt: '2024-07-12T12:52:30.757399Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-07-12 12:52:34'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-12 12:52:38'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
